// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lea_q1rh0TqXGta_WaRhe1sb53zU500',
    appId: '1:56813302812:web:80501fb838f3f86ec91bd9',
    messagingSenderId: '56813302812',
    projectId: 'bamtol-market-son',
    authDomain: 'bamtol-market-son.firebaseapp.com',
    storageBucket: 'bamtol-market-son.firebasestorage.app',
    measurementId: 'G-ZNL9H39Y0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcecK8BZU9iGtJ2N3hioRzHvwJAjxciFU',
    appId: '1:56813302812:android:52fd987127ead56ec91bd9',
    messagingSenderId: '56813302812',
    projectId: 'bamtol-market-son',
    storageBucket: 'bamtol-market-son.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzrGv3a22xsx12SKN0u9NNpCFBYXuw5GI',
    appId: '1:56813302812:ios:01bb6b5e8a6d9db4c91bd9',
    messagingSenderId: '56813302812',
    projectId: 'bamtol-market-son',
    storageBucket: 'bamtol-market-son.firebasestorage.app',
    iosBundleId: 'com.devman.cloneapp.bamtolMarketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6lea_q1rh0TqXGta_WaRhe1sb53zU500',
    appId: '1:56813302812:web:93baad6da2aa75f3c91bd9',
    messagingSenderId: '56813302812',
    projectId: 'bamtol-market-son',
    authDomain: 'bamtol-market-son.firebaseapp.com',
    storageBucket: 'bamtol-market-son.firebasestorage.app',
    measurementId: 'G-9118TC4RBP',
  );
}
